version: '3.7'

services:
  django:
    build: ./backend
    command: python start.py
    volumes:
      - ./backend/:/code/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  angular:
    build: ./frontend
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
      - ./frontend/:/code/frontend
    ports:
      - 4200:4200
    env_file:
      - ./frontend/.env