version: '3.7'

services:
  django:
    build: ./backend
    command: bash ./start.sh
    volumes:
      - ./backend/:/code/backend
      - static_volume:/code/backend/static
    expose:
      - 8000
    env_file:
      - ./.env

  angular:
    build: ./frontend
    command: bash ./start.sh
    volumes:
      - ./frontend/:/code/frontend
      - static_volume:/code/backend/static
    ports:
      - 4200:4200
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django
    volumes:
      - static_volume:/code/backend/static

volumes:
  static_volume: