version: '3.7'

services:
  django:
    build: ./backend
    command: sh ./start.sh
    volumes:
      - ./backend/:/code/backend
      - static_volume:/code/backend/static
    expose:
      - 8000
    env_file:
      - ./backend/.env

  angular:
    build: ./frontend
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
      - ./frontend/:/code/frontend
    ports:
      - 4200:4200
    env_file:
      - ./frontend/.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django
    volumes:
      - static_volume:/code/backend/static

volumes:
  static_volume: