# Generated by Django 3.1.3 on 2020-11-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20201111_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('name', 'state')},
        ),
    ]
